import type {
  CharacterId,
  CombatSessionId,
  ItemDefId,
  ItemInstanceId,
  TickNumber,
} from '@lod/shared-utils';

/**
 * Core character/enemy statistics. HP is the current value; HP_MAX is the
 * upper bound used by heal clamping. STR drives close-combat damage, DEX
 * drives hit chance and long-range marksmanship, AGL drives dodge, flee, and
 * initiative.
 */
export interface Stats {
  str: number;
  dex: number;
  agl: number;
  hp: number;
  hpMax: number;
}

/** 2D integer tile coordinate within a sector's tile grid. */
export interface TileCoord {
  x: number;
  y: number;
}

/**
 * Eight-direction movement. Diagonal moves cost more on the map but are
 * supported everywhere a move can be issued.
 */
export type Direction = 'N' | 'S' | 'E' | 'W' | 'NE' | 'NW' | 'SE' | 'SW';

/**
 * Entity IDs in combat may be real characters (`CharacterId`) or transient
 * enemies (plain strings generated by the encounter spawner). Keep this union
 * loose so enemies don't need their own branded type.
 */
export type EntityId = CharacterId | string;

/**
 * Combat phase state. LongRange is the opening phase when combatants are more
 * than one tile apart; CloseCombat begins once everyone is adjacent or the
 * round cap expires; Resolution is the terminal phase used to freeze the
 * session while the outcome and loot are finalized.
 */
export type CombatPhase = 'LongRange' | 'CloseCombat' | 'Resolution';

/**
 * Weapon definition as consumed by the formulas. `base` and `variance` feed
 * into `roll(base, base + variance)`. `accuracy` is an additive bias on the
 * hit-chance formula; must be in [-0.20, +0.20] to keep clamped outputs
 * meaningful.
 */
export interface WeaponDef {
  id: ItemDefId;
  name: string;
  kind: 'close' | 'long';
  base: number;
  variance: number;
  accuracy: number;
  /** Only meaningful for `kind: 'long'`. Distance beyond this triggers falloff. */
  optimalRange?: number;
}

/** Armor definition with split mitigation for close and long-range damage. */
export interface ArmorDef {
  id: ItemDefId;
  name: string;
  soak: number;
  soakLong: number;
}

/**
 * A participant in a combat session. `team` is used for PvE (player team `A`
 * vs. enemy team `B`) and symmetric PvP. `medkitsUsedThisSession` enforces the
 * 3-per-session medkit cap described in the combat design.
 */
export interface Combatant {
  id: EntityId;
  stats: Stats;
  team: 'A' | 'B';
  weaponLong?: WeaponDef;
  weaponClose?: WeaponDef;
  armor?: ArmorDef;
  position: TileCoord;
  medkitsUsedThisSession: number;
  initiative: number;
  isAlive: boolean;
}

/**
 * Re-exports so downstream consumers that only import from `@lod/game-core`
 * can still reach the branded IDs they need for typing combat sessions.
 */
export type {
  CharacterId,
  CombatSessionId,
  ItemDefId,
  ItemInstanceId,
  TickNumber,
};
